name: ACoreSpigotAPI
version: 2.0.0
main: fr.acore.spigot.ACoreSpigotAPI
api-version: 1.8.8
author: azefgh456
description: A test Plugin
softdepend: [Vault, Essentials, Factions, RandomTP, WorldGuard]
commands:
  reload:
    aliases: [rl]