package fr.azefgh456.acore.jedis.pubsub.action;

public enum JedisActions {
	
	INIT_SERVER,
	STOP_SERVER,
	UPDATE_SERVER,
	ADD_HUB,
	REMOVE_HUB,
	PLAYER_REMOVE,
	PLAYER_ADD,
	PING_GLOBAL,
	TELEPORT_PLAYER,
	PLAYER_CHANGE_SERVER, 
	SEND_PLAYER_MESSAGE, 
	CHECK_UPDATE_MODULE,
	ADD_PLAYER_TO_SERVER_QUEUE,
	REMOVE_PLAYER_TO_SERVER_QUEUE,
	GET_SERVER_INFORMATION;

}
